version: '3'

services:
  spark:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/home/jovyan/workspace:cached

    environment:
      GRANT_SUDO: "1"

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs spark on the same network as the kafka container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:kafka

    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode

    # Use "forwardPorts" in **devcontainer.json** to forward an spark port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  zookeeper:
    image: docker.io/bitnami/zookeeper:3.7
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:3
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper


  # influxdb:
  #   image: influxdb:1.8
  #   ports:
  #     - "8086:8086"
  #   environment:
  #     - DOCKER_INFLUXDB_INIT_MODE=setup
  #     - DOCKER_INFLUXDB_INIT_USERNAME=bdho-kappa
  #     - DOCKER_INFLUXDB_INIT_PASSWORD=bdho-kappa7865223
  #     - DOCKER_INFLUXDB_INIT_ORG=ugent
  #     - DOCKER_INFLUXDB_INIT_BUCKET=kappa-bucket
